const data = {
  products: [
    {
      _id: 1,
      name: 'Top brown top',
      category: 'Jacekt',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'CottonOn',
      rating: 4.5,
      numReviews: 10,
      description: 'Baggy smooth jersey',
    },
    {
      _id: 2,
      name: 'Jacket',
      category: 'Jacket',
      image: '/images/p2.jpg',
      price: 50,
      countInStock: 20,
      brand: 'CottonOn',
      rating: 5,
      numReviews: 10,
      description: 'Brown Jacket',
    },
    {
      _id: 3,
      name: 'Black Suit',
      category: 'Suit',
      image: '/images/p3.jpg',
      price: 1500,
      countInStock: 0,
      brand: 'Versace',
      rating: 5,
      numReviews: 40,
      description: 'Nice suit for men',
    },
    {
      _id: 4,
      name: 'Classic suit',
      category: 'Suit',
      image: '/images/p4.jpg',
      price: 1200,
      countInStock: 15,
      brand: 'D&G',
      rating: 4,
      numReviews: 7,
      description: 'Classic Suit for men',
    },
    {
      _id: 5,
      name: 'Adidas Chief Kit',
      category: 'Jersey',
      image: '/images/p5.jpg',
      price: 99,
      countInStock: 5,
      brand: 'Adidas',
      rating: 5,
      numReviews: 20,
      description: 'Medium sized kit',
    },
    {
      _id: 6,
      name: 'Adidas ManU Kit',
      category: 'Jersey',
      image: '/images/p6.jpg',
      price: 99,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'Man U Jersey',
    },
  ],
};

export default data;
